// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: verify.proto

package verify

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VerifyClient is the client API for Verify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerifyClient interface {
	SendToUserEmail(ctx context.Context, in *EmailVerifyReq, opts ...grpc.CallOption) (*EmailVerifyResp, error)
	VerifyUserEmail(ctx context.Context, in *EmailVerifyReq, opts ...grpc.CallOption) (*EmailVerifyResp, error)
}

type verifyClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifyClient(cc grpc.ClientConnInterface) VerifyClient {
	return &verifyClient{cc}
}

func (c *verifyClient) SendToUserEmail(ctx context.Context, in *EmailVerifyReq, opts ...grpc.CallOption) (*EmailVerifyResp, error) {
	out := new(EmailVerifyResp)
	err := c.cc.Invoke(ctx, "/verify.Verify/SendToUserEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifyClient) VerifyUserEmail(ctx context.Context, in *EmailVerifyReq, opts ...grpc.CallOption) (*EmailVerifyResp, error) {
	out := new(EmailVerifyResp)
	err := c.cc.Invoke(ctx, "/verify.Verify/VerifyUserEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifyServer is the server API for Verify service.
// All implementations must embed UnimplementedVerifyServer
// for forward compatibility
type VerifyServer interface {
	SendToUserEmail(context.Context, *EmailVerifyReq) (*EmailVerifyResp, error)
	VerifyUserEmail(context.Context, *EmailVerifyReq) (*EmailVerifyResp, error)
	mustEmbedUnimplementedVerifyServer()
}

// UnimplementedVerifyServer must be embedded to have forward compatible implementations.
type UnimplementedVerifyServer struct {
}

func (UnimplementedVerifyServer) SendToUserEmail(context.Context, *EmailVerifyReq) (*EmailVerifyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToUserEmail not implemented")
}
func (UnimplementedVerifyServer) VerifyUserEmail(context.Context, *EmailVerifyReq) (*EmailVerifyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUserEmail not implemented")
}
func (UnimplementedVerifyServer) mustEmbedUnimplementedVerifyServer() {}

// UnsafeVerifyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifyServer will
// result in compilation errors.
type UnsafeVerifyServer interface {
	mustEmbedUnimplementedVerifyServer()
}

func RegisterVerifyServer(s grpc.ServiceRegistrar, srv VerifyServer) {
	s.RegisterService(&Verify_ServiceDesc, srv)
}

func _Verify_SendToUserEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailVerifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyServer).SendToUserEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verify.Verify/SendToUserEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyServer).SendToUserEmail(ctx, req.(*EmailVerifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verify_VerifyUserEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailVerifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyServer).VerifyUserEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verify.Verify/VerifyUserEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyServer).VerifyUserEmail(ctx, req.(*EmailVerifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Verify_ServiceDesc is the grpc.ServiceDesc for Verify service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Verify_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "verify.Verify",
	HandlerType: (*VerifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendToUserEmail",
			Handler:    _Verify_SendToUserEmail_Handler,
		},
		{
			MethodName: "VerifyUserEmail",
			Handler:    _Verify_VerifyUserEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verify.proto",
}
